services:
  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file: "./backend/.env"
    depends_on:
      - valkey
      - postgres
    develop:
      watch:
        - action: sync
          path: ./backend 
          target: /usr/src/app
          ignore:
            - out/
  valkey:
    image: valkey/valkey:7.2.5-alpine
    restart: unless-stopped
  postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toronto_wild
  caddy: 
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
